### PR TITLE
Issue223 ng dyanmic forms generate groups or fieldsets

### PR DESCRIPTION
**Pull request by Skidush**
Issue: https://github.com/cristal-ise/cristal-ise/issues/223

### CODE REVIEW

**Comment by taurus227** [comment]
Make containerGrid configurable: https://github.com/cristal-ise/cristal-ise/blob/961282814debd8db0c883eccb43b36c092556e73/xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/DataRecord.java#L203

**Comment by kovax** [comment]
Check this line in DataRecord, adding the Name of the DataRecord as label is commented:

https://github.com/cristal-ise/cristal-ise/blob/961282814debd8db0c883eccb43b36c092556e73/xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/DataRecord.java#L218

**Comment by Skidush** [comment]
> Check this line in DataRecord, adding the Name of the DataRecord as label is commented:
> 
> https://github.com/cristal-ise/cristal-ise/blob/961282814debd8db0c883eccb43b36c092556e73/xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/DataRecord.java#L218

Uncommenting it would put the schema name on top (which I think is undesired) so I placed it in the dynamicForms in the mean time.

image

**Comment by kovax** [comment]
Yes, but that very same code adds the label for the other fieldsets as well. So can implement that the top level DataRecord should not add the label, but the other should. and we can overwrite the label by the dyanmicForms field. This is how it works for the fields.

**Comment by Skidush** [comment]
I see. I'll take a look into it

**Comment by kovax** [comment]
the OutcoeBuilder holds the reference `modelRoot` to the root DataRecord, so add a `boolean isRoot = false` to the OutcomeStructure and set it to true in OutcoeBuilder.

**Pull request merged**
